package annotation;


public enum BaekjoonTier {

    UNDEFINED,

    BRONZE_I, BRONZE_II, BRONZE_III, BRONZE_IV, BRONZE_V,

    SILVER_I, SILVER_II, SILVER_III, SILVER_IV, SILVER_V,

    GOLD_I, GOLD_II, GOLD_III, GOLD_IV, GOLD_V,

    PLATINUM_I, PLATINUM_II, PLATINUM_III, PLATINUM_IV, PLATINUM_V,

    DIAMOND_I, DIAMOND_II, DIAMOND_III, DIAMOND_IV, DIAMOND_V,

    RUBY_I, RUBY_II, RUBY_III, RUBY_IV, RUBY_V,
}


